version: "3.4"

networks:
  net:
    name: gameloan
    external: false

volumes:
  mongovolume:
    name: gameloan-mongo-volume
    driver: local

services:
  mongo:
    image: mongo
    container_name: gameloan-mongodb
    hostname: mongodb
    networks:
      - net
    volumes:
      - mongovolume:/data/db
    ports:
      - 9007:27017

  api:
    image: gameloan-api
    container_name: gameloan-api
    build:
      context: src/Services/GameLoan/
      dockerfile: Dockerfile
    ports:
      - 9000:80      
    environment:
      - MongoDb:Connection=mongodb://mongodb
      - ASPNETCORE_URLS=http://+:80
    networks:
      - net
    depends_on:
      - mongo

  web:
    image: gameloan-web
    container_name: gameloan-web
    build:
      context: src/Web/ReactSPA
      args:
        - API_BASE_URL=http://localhost:9000
        - NODE_ENV=Development
    ports:
      - 9001:80
    networks:
      - net
    depends_on:
      - api
